---
title: 'Research Progress & Planning'
output:
  workflowr::wflow_html:
              toc: true
              toc_depth: 4
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
```

```{css style settings, echo = FALSE}
blockquote {
    padding: 10px 20px;
    margin: 0 0 20px;
    font-size: 14px;
    border-left: 5px solid #eee;
}
```

## Goal

**This document captures the core logic, insights, and evolving ideas behind the project. It serves as a space to refine my thinking and outline the conceptual steps that will guide the analysis.**


## Background

The detailed progress refer to the [2025 progress](https://zq2209.github.io/GradPLog/2025.html). 

The overall is we have identified DPGs and distal genes for IBD, and what's next steps to better understand the disease with what we have.  


## Integrate scRNA and scATAC 

### scRNA

Reveals the functional consequences - which genes are expressed, in which cell types, and how their expression patterns change in disease

1. Determine in which cell types Disease Proximal Genes (DPGs) are expressed and assess whether their expression differs between IBD cases and controls.

  - Dot plot - case vs control
  - UMAP and gene expression plot
  - Which genes drive the high expression in which cell

2. Perform statistical tests to identify DPGs that are significantly enriched or highly expressed in specific cell types.

  - AUCell analysis
  - enrichment analysis of core genes vs common variants (GWAS)










